In [1]:
import torch 

In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f" using GPU : {torch.cuda.get_device_name(0)}")
else: 
    print("GPU is not available")
          

GPU is not available


In [4]:
#tensors

In [5]:
#creating a tensor

In [7]:
torch.empty(2,3)
#allocates a memory  -- these memories were already there in memory

tensor([[-8.4751e-22,  1.3466e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:

torch.rand(2,3)

#random values from zero to one

tensor([[0.7015, 0.4565, 0.0568],
        [0.2325, 0.4899, 0.2292]])

In [24]:
a = torch.rand(1,2)

In [25]:
a

tensor([[0.9857, 0.2636]])

In [26]:
a.shape

torch.Size([1, 2])

In [27]:
a.reshape(-1)

tensor([0.9857, 0.2636])

In [28]:
a.shape

torch.Size([1, 2])

In [29]:
a

tensor([[0.9857, 0.2636]])

In [30]:
#reshaping the tensor 

In [31]:
a = torch.ones(3,4)

In [32]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
a.reshape(2,6)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [35]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])